import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import dynamic from "next/dynamic";

const AuthContextProvider = dynamic(
  () => import("../context/AuthContext.tsx"),
  {
    ssr: false,
  }
);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Makemates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-100`}>
        <AuthContextProvider>
          <Toaster position="bottom-center" />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
